version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    container_name: redis-nt
    ports:
      - "6379:6379"
    command: redis-server --notify-keyspace-events Ex

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-nt
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-nt
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

  app:
    build: .
    container_name: voto-app
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/voto_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  db:
    image: postgres:13-alpine
    container_name: postgres-nt
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: voto_db
    ports:
      - "5432:5432"

