{
 "title": "Default - Votos-Nt",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latência - Abrir Sessão.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "votacao_abrir_sessao_latencia_seconds_sum / votacao_abrir_sessao_latencia_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência - Registrar Voto.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "votacao_voto_latencia_seconds_sum / votacao_voto_latencia_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de Solicitações (Request Rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de Recursos (CPU e Memória)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "__auto"
    },
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Número de Sessões Abertas",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(votacao_sessao_abertas_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Média e Total de Votos por Sessão",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(votacao_total_votos_total) by (pautaId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Tempo de Resposta por Endpoint (Endpoint Latency)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_max{uri=\"/api/votacao/sessao\"}[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=\"/api/votacao/sessao\"}[15m])) \n/ \nsum(rate(http_server_requests_seconds_count{uri=\"/api/votacao/sessao\"}[15m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(http_server_requests_seconds_sum{uri=\"/api/votacao/sessao\"}) \n/ \nsum(http_server_requests_seconds_count{uri=\"/api/votacao/sessao\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3. Latência - Calcular Resultado e Publicar Resultado",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "votacao_voto_latencia_seconds_sum / votacao_voto_latencia_seconds_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "votacao_abrir_sessao_latencia_seconds_sum / votacao_abrir_sessao_latencia_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3. Latência - Calcular Resultado e Publicar Resultado",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4..\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum[1m])) / sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}